In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
#print(x_train.min(), x_train.max())
#print(x_train.shape)
#print(x_test.shape)
#print(x_train[0])

In [3]:
x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train[0])

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.    

In [4]:
print(y_train.shape)
print(y_train[0])

(60000,)
5


###  Building the Network...

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
import copy #needed for copy or deepcopy
x_train_copy = copy.copy(x_train)
print(x_train_copy.shape)
print(x_train_copy[0].flatten().shape)
x_train_copy = x_train_copy.reshape(60000, 28*28)
print(x_train_copy.shape)
print(x_train.shape)

(60000, 28, 28)
(784,)
(60000, 784)
(60000, 28, 28)


In [7]:
x_train = x_train.reshape(60000, 28*28)
x_test = x_test.reshape(10000, 28*28)

In [8]:
model = tf.keras.models.Sequential([
    #tf.keras.layers.Flatten(input_shape=(28, 28))
    tf.keras.layers.Dense(10, activation='relu', input_shape=(784,)),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1])
print(predictions)
predictions = predictions.numpy()
predictions

tf.Tensor(
[[ 0.10740346  0.21996543 -0.01450643  0.04558697 -0.07315651 -0.01446338
   0.09498578  0.09211892  0.04384476  0.3806982 ]], shape=(1, 10), dtype=float32)


array([[ 0.10740346,  0.21996543, -0.01450643,  0.04558697, -0.07315651,
        -0.01446338,  0.09498578,  0.09211892,  0.04384476,  0.3806982 ]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.10111538, 0.11316244, 0.08951019, 0.09505407, 0.08441139,
        0.08951404, 0.09986753, 0.09958164, 0.0948886 , 0.1328947 ]],
      dtype=float32)

### Dense layer size 16, an output layer dense 10, no other layers

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

2.4133599

In [13]:
model = tf.keras.models.Sequential([
    #tf.keras.layers.Flatten(input_shape=(28, 28))
    tf.keras.layers.Dense(16, activation='relu', input_shape=(784,)),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [14]:
model.compile(optimizer='Adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 490us/step - loss: 0.4225 - accuracy: 0.8831
Epoch 2/5
1875/1875 [==============================] - 1s 497us/step - loss: 0.2569 - accuracy: 0.9253
Epoch 3/5
1875/1875 [==============================] - 1s 496us/step - loss: 0.2176 - accuracy: 0.9376
Epoch 4/5
1875/1875 [==============================] - 1s 498us/step - loss: 0.1941 - accuracy: 0.9440
Epoch 5/5
1875/1875 [==============================] - 1s 503us/step - loss: 0.1779 - accuracy: 0.9482


In [16]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.1782 - accuracy: 0.9477


[0.17815014719963074, 0.947700023651123]

### Dense Layer of Size 16

In [17]:
model = tf.keras.models.Sequential([
    #tf.keras.layers.Flatten(input_shape=(28, 28))
    tf.keras.layers.Dense(16, activation='relu', input_shape=(784,)),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [18]:
model.compile(optimizer='RMSProp',
             loss=loss_fn,
             metrics=['accuracy'])

In [19]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 562us/step - loss: 0.4302 - accuracy: 0.8770
Epoch 2/5
1875/1875 [==============================] - 1s 573us/step - loss: 0.2541 - accuracy: 0.9266
Epoch 3/5
1875/1875 [==============================] - 1s 581us/step - loss: 0.2210 - accuracy: 0.9364
Epoch 4/5
1875/1875 [==============================] - 1s 550us/step - loss: 0.2011 - accuracy: 0.9428
Epoch 5/5
1875/1875 [==============================] - 1s 598us/step - loss: 0.1860 - accuracy: 0.9469


In [20]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.1897 - accuracy: 0.9454


[0.1896858662366867, 0.9453999996185303]

In [21]:
model = tf.keras.models.Sequential([
    #tf.keras.layers.Flatten(input_shape=(28, 28))
    tf.keras.layers.Dense(28, activation='relu', input_shape=(784,)),
    tf.keras.layers.Dense(14, activation='relu'),
    tf.keras.layers.Dense(7, activation='relu'),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [22]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 598us/step - loss: 0.4897 - accuracy: 0.8494
Epoch 2/5
1875/1875 [==============================] - 1s 591us/step - loss: 0.2121 - accuracy: 0.9395
Epoch 3/5
1875/1875 [==============================] - 1s 585us/step - loss: 0.1721 - accuracy: 0.9496
Epoch 4/5
1875/1875 [==============================] - 1s 592us/step - loss: 0.1529 - accuracy: 0.9552
Epoch 5/5
1875/1875 [==============================] - 1s 659us/step - loss: 0.1367 - accuracy: 0.9598


In [24]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.1561 - accuracy: 0.9559


[0.15608368813991547, 0.9559000134468079]

In [25]:
model = tf.keras.models.Sequential([
    #tf.keras.layers.Flatten(input_shape=(28, 28))
    tf.keras.layers.Dense(784, activation='tanh', input_shape=(784,)),
    #tf.keras.layers.Dense(14, activation='relu'),
    #tf.keras.layers.Dense(14, activation='relu'),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [26]:
model.compile(optimizer='ftrl',
             loss=loss_fn,
             metrics=['accuracy'])

In [27]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 6ms/step - loss: 2.2996 - accuracy: 0.1651
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 2.0434 - accuracy: 0.3031
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 1.2755 - accuracy: 0.5982
Epoch 4/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.8620 - accuracy: 0.7543
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.6851 - accuracy: 0.8068


In [28]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.6104 - accuracy: 0.8280


[0.6104406714439392, 0.828000009059906]

In [29]:
model = tf.keras.models.Sequential([
    #tf.keras.layers.Flatten(input_shape=(28, 28))
    tf.keras.layers.Dense(28, activation='relu', input_shape=(784,)),
    tf.keras.layers.Dense(14, activation='tanh'),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [30]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [31]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 576us/step - loss: 0.4175 - accuracy: 0.8908
Epoch 2/5
1875/1875 [==============================] - 1s 567us/step - loss: 0.1859 - accuracy: 0.9459
Epoch 3/5
1875/1875 [==============================] - 1s 564us/step - loss: 0.1446 - accuracy: 0.9573
Epoch 4/5
1875/1875 [==============================] - 1s 567us/step - loss: 0.1235 - accuracy: 0.9630
Epoch 5/5
1875/1875 [==============================] - 1s 567us/step - loss: 0.1087 - accuracy: 0.9671


In [32]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.1497 - accuracy: 0.9555


[0.14965833723545074, 0.9555000066757202]